name: python_environment_road
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - geopandas
  - shapely
  - pyproj
  - rtree
  - contextily
  - cartopy
  - statsmodels
  - plotly
  - eurostat
  - ipykernel
